name: AntiCheatPE
main: AntiCheatPE\Main
version: 1.0.1
api: [2.0.0]
author: AntiCheatPETeam
authors: [luca28pet, Fycarman, Survingo]
description: AntiCheat plugin for your PocketMine-MP server!
permissions:
 anticheat.admin:
  description: "Prevent being flagged as hacker"
  default: op
