#AntiCheatPE configuration file
#Authors: luca28pet, Fycarman

#How many times a player must be tagged as hacker before being kicked. Default: 3
tags: 3
#How many times a player must be kicked before an action is executed. Default: 3
kicks: 3
#How many speed points a player must get before an action is executed. Default: 7
points: 7
#Action executed after the number of kicks defined. Options: ban, ban-ip, ban-client, custom. Default: ban-ip
#You can use {player} for the player's name.
#If you have Timerban or EssentialsPE,and you want to temp-ban a player,just the action as the following:
#Action: custom
#Commands: (Note: executed as console!!)
# - broadcast {player} has been banned for hacks.
# - timerbanip add {player} 120
Action: ban-ip
Commands: []
