#    _          _   _  ____ _                _   ____  _____ 
#   / \   _ __ | |_(_)/ ___| |__   ___  __ _| |_|  _ \| ____|
#  / _ \ | '_ \| __| | |   | '_ \ / _ \/ _` | __| |_) |  _|  
# / ___ \| | | | |_| | |___| | | |  __/ (_| | |_|  __/| |___ 
#/_/   \_\_| |_|\__|_|\____|_| |_|\___|\__,_|\__|_|   |_____|

#Authors: luca28pet, Fycarman, Survingo, AryToNeX

#For fly: How many times a player must be tagged as hacker before being kicked. Default: 3
tags: 3
#Fly & Speed: How many times a player must be kicked before an action is executed. Default: 3
kicks: 3
#For speed: How many speed points a player must get before an action is executed. Default: 7
points: 7
#Message used on kick (you can use § for colored messages. Note: showed only if the action is set to ban, ban-ip or ban-client).
kick message: "§4[AntiCheat] §eYou were kicked for using mods/hacks/cheats. Please disable them to play on this server"
#Message used on kick by Damage Hacks (Knockbak, Onehit, No-Damage)
dmgmessage: "§4[AntiCheat] §eDon't use §6Damage §eCheats in this Server!"
#Message used on ban (you can use § for colored messages. Note: showed only if the action is set to ban, ban-ip or ban-client).
ban message: "§4[AntiCheat] §eYou were banned for using mods/hacks/cheats."
#Action executed after the number of kicks defined. Options: ban, ban-ip, ban-client, custom. Default: ban-ip
#You can use {player} for the player's name.
#If you have Timerban or EssentialsPE,and you want to temp-ban a player,just the action as the following:
#Action: custom
#Commands: (Note: executed as console!!)
# - broadcast {player} has been banned for hacks.
# - timerbanip add {player} 120
Action: ban-ip
Commands: []

#Combatlogger plugin (https://github.com/Lambo16/CombatLogger/) by Lambo integration
#Set to true if you want to disable speed and fly hack checking during pvp
clogger: false

#Allow experimental gamemode protection
gamemode-protection: true

#Time to check for gamemode cheaters in seconds
gamemode-time: 5

#Gamemode protection
#Allowed gamemode
gamemode: SURVIVAL

#This will be done if someone cheats gamemode
#Available actions:
#kick - Player will be kicked
#ban - Player will be banned
#ban-ip - IP will be banned
gamemode-action: kick

#Message used on kick/ban/ip-ban
gamemode-message: "§4[AntiCheat] §eYou were kicked for using gamemode mods/hacks/cheats."
